output:
  sort-results: true
linters:
  disable:
    - exhaustivestruct
    - scopelint
    - maligned
  presets:
    - bugs
    - error
    - performance
    - sql
    - test
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goerr113
