output:
  sort-results: true
linters:
  disable:
    - exhaustivestruct
  presets:
    - performance
    - sql
    - test

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goerr113
