output:
  sort-results: true
linters:
  disable:
    - exhaustivestruct # overkill
    - scopelint        # deprecated
    - maligned         # deprecated
    - godox            # to-do comments are fine
    - godot            # comments are fine without full stops
  presets:
    - bugs
    - comment
    - error
    - performance
    - sql
    - test
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goerr113
